### PR TITLE
Fix: returning clause

### LINKED ISSUE #28: Writes using `RETURNING` must use "Query" method
We use some INSERT/UPDATE commands that have a RETURNING clause, so we need to use `.Query` even if we are writing. 

Wouldn't the library use the wrong db connection in this case?

### PR DESCRIPTION
**Pull request by Nasfame**
fix #28

### CODE REVIEW

File: db.go [hunk 1]
```diff
@@ -176,35 +177,41 @@ func (db *sqlDB) PrepareContext(ctx context.Context, query string) (_stmt Stmt,
...
 // QueryContext executes a query that returns rows, typically a SELECT.
 // The args are for any placeholder parameters in the query.
-// QueryContext uses a radonly db as the physical db.
-func (db *sqlDB) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
-	rows, err := db.ReadOnly().QueryContext(ctx, query, args...)
-	if isDBConnectionError(err) {
+func (db *sqlDB) QueryContext(ctx context.Context, query string, args ...interface{}) (rows *sql.Rows, err error) {
+	var curDB *sql.DB
+	query = strings.ToUpper(query)
+	writeFlag := strings.Contains(query, "RETURNING")
```
Comment (bxcodec) [inline db.go:189]: This is so specific to Postgres.
I'm still looking at the idea of how to make it optional or configurable

Comment (bxcodec) [reply db.go:189]: I think it's better to filter based on `INSERT` `UPDATE` and `DELETE` and it's more agnostic to any kind of DB

Comment (Nasfame) [reply db.go]: Ok Thanks the pr is complete

**Comment by Nasfame** [comment]
The pr is complete

**Comment by Nasfame** [comment]
Due to conflicting changes i have rebased #32 here.

**Comment by herpiko** [comment]
Hope this get merged soon!

File: db.go [hunk 2]
```diff
@@ -176,37 +179,53 @@ func (db *sqlDB) PrepareContext(ctx context.Context, query string) (_stmt Stmt,
...
 // QueryContext executes a query that returns rows, typically a SELECT.
 // The args are for any placeholder parameters in the query.
-// QueryContext uses a radonly db as the physical db.
-func (db *sqlDB) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
-	rows, err := db.ReadOnly().QueryContext(ctx, query, args...)
-	if isDBConnectionError(err) {
+func (db *sqlDB) QueryContext(ctx context.Context, query string, args ...interface{}) (rows *sql.Rows, err error) {
+	var curDB *sql.DB
+	_query := strings.ToUpper(query)
+	writeFlag := strings.Contains(_query, "RETURNING")
```
Comment (RangelReale) [inline db.go:191]: This may be triggered if there is a column or table named "RETURNING" exists on the query. 

It won't be a big problem because the query would go to the readwrite connection so it would work anyway, but maybe we should see if there is also "INSERT", "UPDATE", or "DELETE" in the query in addition to "RETURNING", to be a little more safe?

**Comment by bxcodec** [comment]
Wait it contains a lot of changes in 1 PR?

File: db.go [hunk 3]
```diff
@@ -102,7 +105,7 @@ func (db *sqlDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, err
 // The args are for any placeholder parameters in the query.
 // Exec uses the RW-database as the underlying db connection
 func (db *sqlDB) Exec(query string, args ...interface{}) (sql.Result, error) {
-	return db.ExecContext(context.Background(), query, args...)
+	return db.ExecContext(backgroundCtx, query, args...)
```
Comment (RangelReale) [inline db.go:108]: This will make all queries use the same context, which internally use mutexes and channels to protect data structures, I think this may decrease performance under load.

File: db.go (hunk 2 above)
Comment (Nasfame) [reply db.go:191]: but same issue might pop up if we try if any of the tokens or conditions match the keys "insert","update", or "delete". 

Eg:

select id, deleted_at from _table__

File: db.go (hunk 3 above)
Comment (Nasfame) [reply db.go:108]: > Wait it contains a lot of changes in 1 PR?

Well you can merge my 1st #32  , i have already rebased then branch in this PR

Comment (Nasfame) [reply db.go:108]: > This will make all queries use the same context, which internally use mutexes and channels to protect data structures, I think this may decrease performance under load.

@bxcodec @RangelReale look into the contents of context.Background(). Here is it. This is the code for ur ref

image

As you can clearly see 

```
/ Background returns a non-nil, empty Context. It is **never canceled**, has no
// values, and has no **deadline**. It is typically used by the main function,
// initialization, and tests, and as the **top-level Context** for incoming
// requests.

```
Also its not susceptible to cascading terminations of child contexts...

Same applies to TODO

Comment (Nasfame) [reply db.go:108]: @bxcodec the -race tests are passing with 10 Test cases running in parallel !. So the code is concurrent safe.

Earlier tests completion averaged at 8-9sec
Now tests are completing at 5-6sec

Comment (RangelReale) [reply db.go:108]: If you see the [Go source code where db.Exec calls db.ExecPrepared](https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/database/sql/sql.go;l=1647), they call `context.Background()` every time, I think it is better to follow their practices.

Comment (Nasfame) [reply db.go:108]: I don't understand that part either. CPU cycles are unnecessary wasted with redundant library calls.

Therefore I have raised a PR - https://github.com/golang/go/pull/60575

**Comment by RangelReale** [comment]
I think this MR is changing too many things, better to create more than 1 MR @bxcodec

**Comment by Nasfame** [comment]
> I think this MR is changing too many things, better to create more than 1 MR @bxcodec

@bxcodec Kindly consider merging #32 1st

File: version.go [hunk 4]
```diff
@@ -0,0 +1,10 @@
+package dbresolver
+
+// Version is the current release version.
+const Version = "2.1"
+
+// Commit: is the HEAD commit of this [Version]
+const Commit = "4d12938cb692ad29618ab3b38b05fc4540948d6a"
+
+// ReleaseTime is the UTC Time of the release of this [Version]
+const ReleaseTime = "2023-06-04T03:34:16Z"
```
Comment (bxcodec) [inline version.go:10]: Why do we need this?

Comment (Nasfame) [reply version.go:10]: It becomes easier when debug issues related particular versions. I am working on ISSUE Template that would need the version of dbresolver. 


But i need to clear the values...

Comment (Nasfame) [reply version.go]: We can a have it a separate PR if required. I kept it in this realizing that this is first PR that fixes an issue reported.

**Review by Nasfame — COMMENTED** [review]
Looks good

File: fuzz.go [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+}
+
+func Fuzz(data []byte) int {
+
+	var rdbCount, wdbCount, lbPolicyID uint8
+
+	fuzz.NewFromGoFuzz(data).Fuzz(&rdbCount)
+	fuzz.NewFromGoFuzz(data).Fuzz(&wdbCount)
+	fuzz.NewFromGoFuzz(data).Fuzz(&lbPolicyID)
+
```
Comment (bxcodec) [inline fuzz.go:28]: what is this ?

can we separate this into another PR, this is really not relevant.

Comment (Nasfame) [reply fuzz.go:28]: sure

**Review by bxcodec — APPROVED** [review]
LGTM
